apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.app_name }}
  description: Python app that displays time named ${{ values.app_name }}
  annotations:
    github.com/project-slug: aumthakkar/${{ values.app_name }}
    backstage.io/techdocs-ref: dir:. # (This one is for Techdocs) 
spec:
  type: service
  owner: development # this is the group we have to create as entities/groups.yaml file as shown below:
  lifecycle: experimental